### ISSUE TITLE
`two` property is null

### ISSUE THREAD

**Issue by tommysqueak** [kmkzt/react-hooks-svgdrawing#13]
Hi 👋 

When I use the hook and access the `two` property, it is null because the value is not set until the component is mounted via `useEffect`.

I think the fix is to change this line https://github.com/kmkzt/react-hooks-svgdrawing/blob/8be3e50343bca8569ae021d3412768f36bbece74/src/useDrawing.ts#L65 and return  something like:

```
  return [
    renderRef,
    {
      drawingRef,
      changePenWidth,
      changePenColor,
      clear,
      undo,
      getSvgXML,
      download
    }
  ]
```

`drawingRef.current` can then be used after the component is mounted (eg a handler) to get access to the `two` instance. 

Does this make sense? I can submit a PR if this is a good solution to the issue. Any feedback is appreciated, thanks 🙇 

For context, this is how I'm using it:

```
const SketchPad = () => {

  const [renderRef, action] = useSvgDrawing({
    penWidth: 5,
  })

  const handleDrawingCompleted = useCallback(() => {
    //  Do stuff with action.two but it's null the first time the component renders.

  }, [action])

  return (
    <div
      ref={renderRef}
      onTouchEnd={handleDrawingCompleted}
      onMouseUp={handleDrawingCompleted}
    />
  )
}

```

**Comment by kmkzt** [comment]
@tommysqueak 
Sorry for the late reply.
Thank you for reporting the issue.

welcome to contribute!

It would be nice to be able to create some test code and reference use cases as needed.

**Comment by kmkzt** [comment]
I think it will be solved, so close it.
```ts
const [renderRef, { two }] = useSvgDrawing({
  penWidth: 5,
})
const handleDrawingCompleted = useCallback(() => {
  if(!two) return
  // do something
}, [two])
```

**Comment by tommysqueak** [comment]
Sorry for not getting back... it's on my todo list to share some reproducable steps/code. I will try out that suggestion also. Thanks.
