### ISSUE TITLE
Plot other SVG elements within same div?

### ISSUE THREAD

**Issue by wadehenning** [kmkzt/react-hooks-svgdrawing#56]
It is possible to plot other SVG elements within the same `<div/>` as the drawing container?  I would like to be able to plog charts and then annotate them as I talk using `svgdrawing`.  So far when I have tried, the `svgdrawing` surface covers up everything else. Thanks.

**Comment by kmkzt** [comment]
@wadehenning 

Thank you for using.

Unfortunately, it is imposibble now.
Is it possible to solve the problem by preparing a element that encloses annotation and drawing, or by preparing multiple drawing elements?

Just in case, I'll show you how to render multiple svg element.

```js
import React, { useState, useCallback } from 'react'
import { useSvgDrawing } from 'react-hooks-svgdrawing'

export const Example = () => {
  const [renderRef, draw] = useSvgDrawing()
  const [svgobj, setSvgobj] = useState()

  // It is necessary to set the timing to reflect the drawing to multiple elements
  const handleUpdate = useCallback(() => {
    if (!draw.instance) return
    // https://github.com/kmkzt/svg-drawing/blob/v2.1.1/src/svg.ts#L412-L418
    setSvgobj(draw.instance.toJson())
  }, [])
  return (
    <div>
      <div style={{ width: 500, height: 500 }} ref={renderRef} />
      <div>
        <svg width={svgobj?.width || 500} height={svgobj?.height || 500}>
          {svgobj?.paths.map((p) => (
            <path {...p} />
          ))}
        </svg>
        {/** You can add annotations here */}
      </div>
      <button onClick={handleUpdate}>update render</button>
    </div>
  )
}

```

**Comment by wadehenning** [comment]
Thank you for the nice example.  Unfortunately, my goal is to have animated transitions between my charts and plotting all of the charts to the same svg element makes this task easier.
